kind: Pod
apiVersion: v1
metadata:
  name: pods
spec:
    containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/"
        name: pv-storage
    volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
